= 知识与本领

知识与本领是相辅相成的。知识是通过学习和阅读积累而来的，而本领则是通过实践和经验培养出来的。有了丰富的知识，我们才能更好地掌握本领，将知识转化为实际能力。同时，通过不断学习和实践，我们才能不断提升自己的本领，更好地应对生活和工作中的各种挑战。所以，我们要不断学习、实践，不断积累知识和本领，才能成为更好的自己。

== 大学只教知识，不教本领

大学里为啥不教“相声”？我们知道大学里是开设艺术类专业课程的，例如设计，绘画，雕塑，音乐（声乐、器乐、作曲）等等…..

为啥大学不开设相声，小品，评书，曲艺？

因为这些民族艺术低俗吗？歌剧比秦腔和二人转高级吗？都不是，虽然受市场影响曲艺市场太小众，但是相声、小品和二人转需求量巨大，已经形成配套产业。今年尔滨旅游大火，二人转小剧场场场爆满。

既然有需求，且这些文艺工作者就业还不错，至少就业比大学的那些艺术生好，为啥大学不开这类课呢？

而大学所开的钢琴课，毕业就失业，钢琴音乐生上不能去维也纳金色大厅办个人音乐会，也不能欧洲巡回演出，下不能成为优秀键盘手给国内乐队伴奏。更不能进录音棚…… 他们能干啥？三条路，分别是，一教培机构当老师，二琴行做乐器销售，三进体制当音乐老师。

== 师父即知识还教本领

大学的老师教的是知识，他们只掌握了知识，并没有掌握本领。例如说相声的技巧，四门功课，说学逗唱。学会这四门功课的知识就能上台表演吗？答案是不能。

要上台表演，还需要几项技能，例如语言表达能力，表演能力，应变能力…… 这些是老师教不了你的。

所以，如果掌握知识就能表演，那鲁迅、莫言更擅长，事实上在这些大文豪中，只有李敖有这个能力。

是否可能请大师授课？解决上述问题。把郭德纲和于谦请到大学课堂不行吗？我认为也不行。

给他开多少工资？让他用爱发电？郭德纲即是演员也是德云社老板，整日忙于企业管理他有多少时间？

为啥郭德纲能带出好徒弟？

象牙塔里的老师不参与社会演出，严重脱离一线，而郭德纲从未脱离一线。他能教孩子知识还能传授经验。

本领 = 知识 + 经验

有了本领之后进入社会后可以安身立命，但不能成功。

郭德纲还为你提供了平台，人脉等等，这是大学所能提供的吗？

换个角度，大学里是开设“工商管理”课程的，毕业后能做职业经理人吗？

== 老师和师父

老师不为结果负责，学生与老师的关系是契约关系。知识教给你，契约满，毕业之后，没有任何瓜葛，你能否变现是你自己问题。

师父不行，师父教知识，传授经验，提供平台，还要结果负责，甚至被徒弟连累。