= 现在的年轻人为什么越来越喜欢独处？

== 为什么人与人之间的共同语言越来越少？

在互联网出现之前，我们只能从单一渠道获得信息，例如报纸，广播和电视节目中获取资讯信息。这样茶余饭后，也没有太多的娱乐方式，同事，朋友聚在一起，这些大众信息变成了谈资，由于大家接收相同的内容，你一言我一语，谈论相同话题，发表自己的观点，所以我们的共同语言特别多。

互联网出现后，资讯爆炸式出现，网络给人们更多选择，大家不再接受同质化的内容，不再接受单一渠道的信息，人们可以选择自己感兴趣领域的知识，除了官媒，各大门户网站也会发表自己的观点。

移动互联网之后，平台精准推岁，除了自己关注的领域，不再接受其他信息。我们认为海量的信息输入会让人们开阔视野，恰恰相反，互联网加剧人们的信息鸿沟。人们利用互联网不是去学习通识知识，而是深耕自己所在的领域，于是出现了自己领域以外认知为零的现象。

这也导致大家没有共同语言，几乎难找到共同语言的人，两个人在一起尬聊，鸡同鸭讲。

有一种观点，叫做“知识的诅咒”，大概意思就是，你学到的知识，会以一种不显性的方式内化成你的思维模式，即便你可能在思考问题的过程中没有意识到，但实际上你已经不知不觉地遵循了这种思维模式了，这会天然地让拥有某种专业知识的人在和别人交流时形成一种壁垒。

== 当下社会的社交圈层

当下社会的「圈层」被无限细分，从你出生的一刻，被父母和老师外科手术式地剥离你的社交人群，使你的圈层面积越来越小。你本来可以跟任何小朋友过一起玩，父母让你学钢琴，这时你能接触的小朋友就是其他琴童，学画画、学舞蹈…… 你接触的小朋友越来越少。上大学后所选志愿、城市、大学、专业。工作后选择行业、领域…… 让你的社交圈层无限细分，两个圈子里的人几乎不产生交集，很难接触圈外的人。

这也是为什么会出现大龄剩男和剩女的原因之一，圈子太小，僧多肉少。

这些还是看得见的圈层，还有很多被无形划分的圈层，圈中圈，即使你们都在一个微信群中，也没有社交交集。


== 打工人的生活现状

人的一生大约有三分之一的时间是在工作中度过的，那是欧美发达国家，中国人的工作时间远远超过8小时。

正常的时间分配是将24小时分成三份，分别是：8小时工作，8小时睡觉，8小时生活（自由支配），这是最理想的状态，最后这8小时非常重要，你可以用它来娱乐，社交，学习，等等…… 只有「文明」的发达国家能做到。

而在我们高速发展中国家，工作时间远远超过8小时，首先国家不允许我们休息，其次是企业不允许我们休息，最后打工人自己也不放过自己。这个制度是国家顶层者制定的，因为我们是发展中国家，赶英超美所必需付出的代价。

注意这8小时生活时间，你无法100%支配和利用，例如至少有2个小时被上班的通勤时间所占用，你还需要洗衣、买菜、做饭、打扫卫生，又占用了你1小时。此时你只有 3 小时的自由支配时间。

996和007常态下，打工人如同卓别林的电影《摩登时代》，公司将打工人可以自由支配的3小时全部给压榨了。

所以！年轻人根本没有时间社交。同时我们娱乐方式也变得多样化，人们的私域时间几乎被填充满满的。

== 情绪喂养/情绪输出/情绪决策？

=== 为什么现在的孩子更任性？

现代的孩子是被情绪喂养长大的，我们太照顾孩子的情绪了，当孩子遇到任何问题时，都以孩子心理舒服为底线，满足他们一切需求，只要他们开心即可。

所以孩子学会了用情绪输出来拿捏他们的父母，百试不爽，这给他们造成错觉，对任何人都能情绪输出。

在他们成长的过程中家长的配合，老师的配合，再加上家里老人强化，尽量满足孩子的需求。这让他们误以为输出情绪可以解决一切问题，情绪输出经过反复强化，就会进入思维闭环，于是现代年轻人变成了惯用情绪输出巨婴。

=== 情绪输出

在婚恋市场有个潜规则，护士老师不能娶，大家都这么讲，你问他们为什么不能取，他们却很难说明白。其实造成这种情况的根本原因就是情绪输出老师和护士，把耐心给了学生和患者，情绪和脾气给了家人。

所有服务行业均如此，在甲方、老板、上司、长辈、客户…… 面前受了委屈，无法找到发泄对象，于是就把情绪输出到家人，配偶，孩子，弱者的身上。

=== 情绪输出的代价

进入社会之后，陌生人并不会关心你的情绪，这是被社会毒打的开始。

被情绪操控的人，通常只在乎自己的感受，还会用情绪决策，例如恋爱脑，成也情绪，败也情绪，很多分手的情况，就在情绪的一念之间。

有些人还会将情绪带给家庭，例如孩子、配偶、家里老人等等。

难道你没发现吗？当两个人在一起的，总有一个需要情绪价值，总一个会不知不觉情绪输出，当你独处的时候，这些臭毛病就全没了，你不用在意别人的情绪，你也没有了情绪输出对象，反而生活更容易了。

== 莫把「孤独」当「寂寞」

什么是孤独？孤独时高处不胜寒，独孤求败，是指你在某个领域做到极致，没有懂你，理解你的人和朋友，这是孤独。

什么是寂寞？空虚寂寞冷，没有人陪伴，需要抱团取暖，需要倾诉，受到心理和生理上的双重折磨，这是寂寞。

我很享受孤独，在我的时间和空间里，喜欢一个人安静的看书，一个人静心的品茶和咖啡，一个人享受美食，一个人安静的思考，去创作…… 喜欢这种独处带来的安详。

我不太喜欢跟人交流，我们的认知不在一个层次上，无法沟通，无法理解。

人们只是孤独，治愈寂寞，有无数种方式和方法可以解决寂寞。

== 向下沟通成本

为什么越来越多的人不发朋友圈了？

朋友圈有两重意义，记录自己的生活，展示自己的生活。但是朋友圈关系太复杂，你不可能照顾到每个人，尤其是你身在上流社会，你慢慢就会失去向下沟通的能力，即跟穷人说话的能力，你不经意一句话，你自己没有意识到，对于听者就是拿刀子狠狠扎他。例如：

亲戚：你朋友圈中发的化妆品多少钱呀，我也想买一套。

你说：不贵才1W多快，去香港买的

你脱口而出，你似乎什么都没有意识到，你平时跟你的闺蜜小姐妹也是这么讲的，可是你的闺蜜跟你是同一阶层，他们不会有任何不适。你乡下的亲戚，月薪5000不到，在她看来你在炫富，你在戏耍她，你在看他出丑……

混的好的人会天天发朋友圈，混的不如意的，就只能悄悄离开。

你混的好，别人会把你拉黑，你看不到他的朋友圈，他也不想看你的朋友圈，看你每天打卡，做瑜伽，购物，旅游，各种买买买。

现实中是存在圈层壁垒的，不同圈层是不交集的，两个阶层相安无事，你是看不到别人的私人生活的。互联网的出现打破了圈层壁垒，让各种圈层的人聚集到了一个平台，一句话都可能会得罪某个圈层的人，你无法照顾每个圈层的感受，向下沟通的成本是很高的，最好的选择就是闭嘴。

所以，很多时候，不是你想独处，随着你社会地位的升上，你身边的朋友会不知不觉地离开你。