#!/bin/sh 
# 
# Startup / shutdown script for Clam Antivirus 
CLAMAV=/usr/local/clamav/bin

    case "$1" in 
       start) 
           ${CLAMAV}/sbin/clamd
           ${CLAMAV}/bin/freshclam -d -c 2 -l /var/log/freshclam.log 
           echo -n ' freshclam' 
           ;; 

       stop) 
           /usr/bin/killall freshclam > /dev/null 2>&1 \ 
           && echo -n ' freshclam' 
           ;; 

          *) 
           echo "" 
           echo "Usage: `basename $0` { start | stop }" 
           echo "" 
           exit 64 
           ;; 
    esac 

