= 给Sora泼盆冷水
Firstname Lastname <author@asciidoctor.org>
3.0, July 29, 2022: AsciiDoc article template
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Sora 具有颠覆性吗？我承认有，包括所有AI工具；那么它能提高工作效率吗？的确能。

但是它改变不了打工人的工作现状。

市场主要由两个角色组成，生产者和消费者，我们管生产者称为供给侧，消费者称为需求侧。

无论是ChatGPT还是Sora 是对供给侧的颠覆性革命，它们解决了供给侧的生产效率，原先很多由人负责的工作，现在正在被AI人工智能，以可见的速度替代。人工智能的效率是人的5倍，10倍，100倍……。

现在我要泼冷水了，可是需求侧并没有改变，这跟传统互联网一样，用户并不是线性无限增长的，AI是对存量用户做升级。

既然用户数量不变，用户可支配的屏幕时间是不变的，用户画像和消费习惯不变，推荐引擎算法仍然有效。最后拼的仍然是信息内容质量。

也就是需求侧的创作者们，疯狂加倍输出，原来一天做一个视频，现在一天可以做100个，但是需求侧是没有变化的，看的人还是那么多，花在屏幕上的时间还是那么多。


人工智能并不能让视频质量变高，仅仅是提高了生产效率，内容质量最终还是取决于人。20年前谷歌颠覆搜索引擎，我们互联网从业者率先吃到了搜索引擎红利，让我们工作效率倍增。

工作中我发现很多人是不会用搜索引擎的，他们搜索不到自己想要的东西，必须经过曲折的经历和海量检索才能找到自己想要的内容。

让搜索引擎成为自己的得力助手，需要具备一种能力，就是把自己要搜索的内容，抽象出一些关键字，通过关键字组合，就能快速找到对自己有价值的信息。可是，恨的很多人不具备这种能力，即使工作多年的老员工。这就造成了职场底层员工始终工作在底层，用不好工具。而那些升迁快的员工，总能掌握最新技术，让这些工具成为自己的助手，增加职场核心竞争力。

我在 ChatGPT 上也发现了这种现象，就跟当年的所有引擎一样，基层员工不会用，用不好，也发挥不出AI的优势。人工智能的提示词比搜索引擎的关键字使用门槛更高，Sora 也会同样存在这个问题，并不是一个道具，一个灯光师，化妆师拥有了 Sora 就能自己生成电影了。

说白了，你使用AI的上线，就是你认知的上线，你能干的工作，AI就是你的助手，让你如虎添翼，干的更好，你干不了的工作，AI也帮不了你，总之！你干不了你认知以外的工作。

是我们在用数据训练AI，还是AI再用算法训练我们？

最初是我们使用数据来训练AI，现在是AI通过推送来影响我们，很多人没有意识到，我们一直在被各种算法影响。 甚至被算法压榨，例如外卖小哥，快递小哥，滴滴司机。

就如我前面所说的基层员工，很有可能未来，是AI人工智能给你们安排工作。

例如这样：

公司2024年第一季度销售计划，销售额需要达到200万，我现在有10个业务员下属，小明80后入职3年，小红26岁刚刚结婚，小李上个月的销售冠军，其他下属均是实习生，请问我怎么分解销售任务，请做到量化STAR原则，另外月底需要末位淘汰3人。